#!/usr/bin/env bash
# sets up a new 404 error page
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo chmod -R 755 /var/www
sudo service nginx start
file=/etc/nginx/sites-enabled/default
phrase="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
phrase1="error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\nallow all;\ninternal;\n}"
sudo sed -i "50i $phrase" $file
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sudo sed -i "51i $phrase1" $file
sudo service nginx restart
