#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page
# that contains the string Ceci n'est pas une page.
sudo apt-get update
sudo apt-get install -y nginx 
echo "Hello World!" > index.html
sudo mv index.html /var/www/html

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
echo "Ceci n'est pas une page" > custom_404.html
sudo mv custom_404.html /usr/share/nginx/html

SERVER_CONFIG=\
"server {
	listen 80 default_server;
        listen [::]:80 default_server;
   
        root /var/www/html;
        index index.html;
        server_name _;
	location / {
           try_files \$uri \$uri/ =404;
        }
         if (\$request_uri ~* redirect_me){
	   return 301 https://github.com/MmaGod1;
        }
	error_page 404 /custom_404.html;
        location /custom_404.html{
           root /usr/share/nginx/html;
           internal;
        }
}"
echo "$SERVER_CONFIG" > default
sudo mv default /etc/nginx/sites-available/default
sudo service nginx restart
