#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo chmod -R 755 /var/www
file=/etc/nginx/sites-enabled/default
string=$hostname
phrase="rewrite ^/redirect_me https://github.com/MmaGod1 permanent;"
phrase1="error_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\troot /usr/share/nginx/html;\n\tinternal;\n\t}"
phrase2="add_header X-Served-By \$hostname;"
sudo sed -i "50i $phrase2" $file
sudo sed -i "51i $phrase" $file
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo chmod -R 755 /var/www
sudo sed -i "52i $phrase1" $file
sudo service nginx restart
