#!/usr/bin/env bash
# Installs and setup haproxy on your lb-01 server.

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy

echo "ENABLED=1" > /etc/default/haproxy

# Listen to servers: web1 and web2
echo "
   backend http_back
        balance roundrobin
        server web-01 54.144.222.121:80 check
        server web-02 54.160.95.100:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
